model_type: resmlp_36_224.fb_distilled_in1k
image_size: 224 
patch_size: 16 
mlp_ratio: [4.0, 4.0]
depth: 36
projection_dim: 384
block_layer: res_block 
mlp_layer: mlp
act_layer: gelu
norm_layer: affine